// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxRavIfi_9HtXpTCaskiJRdPfGvU8R5xE',
    appId: '1:754929612827:web:a9448e425adf7450d960be',
    messagingSenderId: '754929612827',
    projectId: 'mobilapp-2dfad',
    authDomain: 'mobilapp-2dfad.firebaseapp.com',
    storageBucket: 'mobilapp-2dfad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKXgf-u3gYxqC0ZqzSdBnMQtb7HxSE-CQ',
    appId: '1:754929612827:android:2bd80099d28e32b0d960be',
    messagingSenderId: '754929612827',
    projectId: 'mobilapp-2dfad',
    storageBucket: 'mobilapp-2dfad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUjV5SNPtD4fqIK5ZorvPqpjAdTbfw0aQ',
    appId: '1:754929612827:ios:6e6cdcde5dcd9389d960be',
    messagingSenderId: '754929612827',
    projectId: 'mobilapp-2dfad',
    storageBucket: 'mobilapp-2dfad.appspot.com',
    iosBundleId: 'com.example.mobilfinalproje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUjV5SNPtD4fqIK5ZorvPqpjAdTbfw0aQ',
    appId: '1:754929612827:ios:82395c6acf734b84d960be',
    messagingSenderId: '754929612827',
    projectId: 'mobilapp-2dfad',
    storageBucket: 'mobilapp-2dfad.appspot.com',
    iosBundleId: 'com.example.mobilfinalproje.RunnerTests',
  );
}
